#!/usr/bin/env bash
#
# oss-init.sh — generate a bootable, ZERO-EXTERNAL-KEY .env for the OSS-light core.
#
# Writes ONLY the [REQUIRED — core boot] set from .env.example, with every secret
# minted from a CSPRNG (openssl rand / Fernet). No OpenAI / Google / GitHub-App /
# Anthropic key is emitted — the 10-service core (nginx, postgres, qdrant, memory-api,
# minio, centrifugo, mcp-brain, mcp-gateway, mcp-scraper, brain-janitor) boots and the
# keyless doc-ingest + local-embeddings + semantic-retrieval path works with this file
# alone (D-16-01). Add ONE optional LLM key afterwards for chat/extraction enhancements.
#
# This is the lowest-friction "docs alone" bootstrap: `make oss-init` and you have a
# core .env in one command, no secret to paste.
#
# Usage:
#   bash infrastructure/scripts/oss-init.sh [--force] [--out PATH | PATH]
#   make oss-init                 # writes ./.env (refuses to clobber an existing one)
#   make oss-init ARGS=--force    # overwrite an existing ./.env
#
# Exit code:
#   0 — wrote the file
#   1 — target exists and --force not given, or a prerequisite is missing
#   2 — bad usage

set -euo pipefail

FORCE=0
OUT=".env"

usage() {
  sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'
}

while [ $# -gt 0 ]; do
  case "$1" in
    -f|--force) FORCE=1; shift ;;
    --out)      OUT="${2:?--out needs a path}"; shift 2 ;;
    -h|--help)  usage; exit 0 ;;
    --)         shift; break ;;
    -*)         echo "oss-init: unknown flag '$1'" >&2; exit 2 ;;
    *)          OUT="$1"; shift ;;
  esac
done

if ! command -v openssl >/dev/null 2>&1; then
  echo "FATAL: openssl is required to mint CSPRNG secrets but was not found on PATH." >&2
  exit 1
fi

if [ -e "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo "REFUSING: '$OUT' already exists. Re-run with --force to overwrite it." >&2
  echo "  (oss-init never edits a file in place — it always writes a fresh core .env.)" >&2
  exit 1
fi

# --- Mint secrets (CSPRNG only — never fixed/placeholder values, T-16-02-01) ---------------------
PW="$(openssl rand -hex 24)"                       # Postgres password — reused verbatim in DATABASE_URL
BRIDGE_SECRET="$(openssl rand -hex 32)"
CENTRIFUGO_HMAC="$(openssl rand -hex 32)"
CENTRIFUGO_API="$(openssl rand -hex 32)"
MINIO_PW="$(openssl rand -hex 16)"                 # 32 hex chars — well above MinIO's 8-char floor (T-16-02-02)

# A valid Fernet key (urlsafe base64 of 32 bytes). Prefer the real generator; the openssl
# fallback is made urlsafe so its FORMAT is still a valid Fernet key when python/cryptography
# is unavailable.
FERNET_KEY_VAL="$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' 2>/dev/null \
  || openssl rand -base64 32 | tr '+/' '-_' | tr -d '\n')"

# --- Write the file. Clean KEY=value lines, NO trailing inline comments (Pitfall 5) --------------
# Header comment lines contain no '=' so the "no trailing inline comment" grep stays clean.
umask 077
# umask only constrains NEWLY created files. With --force over a pre-existing
# .env, `cat >` truncates but KEEPS the old (possibly world-readable) mode, so
# chmod explicitly after writing — this file holds every generated secret.
cat > "$OUT" <<EOF
# xbrain OSS-light core — generated by oss-init.sh
# Zero external keys. Secrets are CSPRNG. Never commit this file.

# --- Edition & profiles ---
EDITION=oss
COMPOSE_PROFILES=

# --- PostgreSQL ---
POSTGRES_USER=xbrain
POSTGRES_PASSWORD=${PW}
POSTGRES_DB=xbrain
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
DATABASE_URL=postgresql+asyncpg://xbrain:${PW}@postgres:5432/xbrain

# --- Cross-service auth ---
BRIDGE_SHARED_SECRET=${BRIDGE_SECRET}
JWT_ALGORITHM=HS256
LOG_LEVEL=INFO

# --- Qdrant ---
QDRANT_URL=http://qdrant:6333

# --- Centrifugo ---
CENTRIFUGO_TOKEN_HMAC_SECRET=${CENTRIFUGO_HMAC}
CENTRIFUGO_API_KEY=${CENTRIFUGO_API}
CENTRIFUGO_HTTP_URL_INTERNAL=http://centrifugo:8000

# --- memory-api ---
MEMORY_API_URL=http://memory-api:8000

# --- Embeddings (local, keyless) ---
EMBEDDINGS_PROVIDER=local
LOCAL_EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
UVICORN_WORKERS=1

# --- Domain / OAuth identity (localhost defaults — change for a real deploy) ---
XBRAIN_BASE_DOMAIN=localhost
OAUTH_ISSUER_URL=http://localhost:8000
OAUTH_RESOURCE_URL=http://localhost:8000/mcp
CORS_ALLOWED_ORIGIN_REGEX='(chrome-extension://.*|http://localhost(:\d+)?)'
AGENT_MENTION_ALIASES=agent
OAUTH_CREDENTIALS_ENCRYPTION_KEY=${FERNET_KEY_VAL}

# --- MinIO / object storage (>= 8-char root password so the core minio never crashloops) ---
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_PW}
MINIO_ENDPOINT=minio:9000
MINIO_BUCKET=xbrain-media
EOF

# Enforce owner-only perms even when --force overwrote a pre-existing, laxer file.
chmod 600 "$OUT" 2>/dev/null || true

# --- Operator banner (stdout only — never written into the .env) ---------------------------------
echo "oss-init: wrote a zero-external-key OSS-light core env to '$OUT'."
echo
echo "  Boots the 10-service core with NO OpenAI / Google / GitHub / Anthropic key."
echo "  Doc ingest + local embeddings + semantic retrieval are keyless."
echo
echo "  OPTIONAL next steps:"
echo "    - Add ONE LLM key (ANTHROPIC_API_KEY | OPENAI_API_KEY | XAI_API_KEY) for"
echo "      in-chat agent + LLM extraction (not required for the SC#3 zero-key flow)."
echo "    - For a NON-localhost deploy, set XBRAIN_BASE_DOMAIN, OAUTH_ISSUER_URL and"
echo "      OAUTH_RESOURCE_URL to your real domain before 'make deploy'."
echo
echo "  Verify with: make env-check"
